### ISSUE TITLE
Updating a condition results in errors

### ISSUE THREAD

**Issue by heydonovan** [draios/terraform-provider-sysdig#26] opened 2020-05-01 15:50 UTC
We are just writing a simple rule, and changing the condition. We have resulted to just destroying everything, and applying it from scratch (which does seem to work around the issue).

```
2020/05/01 10:47:16 [TRACE] <root>: eval: *terraform.EvalCheckPlannedChange
2020/05/01 10:47:16 [TRACE] EvalCheckPlannedChange: Verifying that actual change (action Update) matches planned change (action Update)
2020/05/01 10:47:16 [TRACE] <root>: eval: *terraform.EvalGetProvider
2020/05/01 10:47:16 [TRACE] <root>: eval: *terraform.EvalReadState
2020/05/01 10:47:16 [TRACE] EvalReadState: reading state for sysdig_secure_rule_falco.thezebra_container_whitelist
2020/05/01 10:47:16 [TRACE] UpgradeResourceState: schema version of sysdig_secure_rule_falco.thezebra_container_whitelist is still 0; calling provider "registry.terraform.io/-/sysdig" for any other minor fixups
2020/05/01 10:47:16 [TRACE] GRPCProvider: UpgradeResourceState
2020/05/01 10:47:16 [TRACE] <root>: eval: *terraform.EvalReduceDiff
2020/05/01 10:47:16 [TRACE] <root>: eval: *terraform.EvalIf
2020/05/01 10:47:16 [TRACE] <root>: eval: terraform.EvalNoop
2020/05/01 10:47:16 [TRACE] <root>: eval: *terraform.EvalApplyPre
2020/05/01 10:47:16 [TRACE] <root>: eval: *terraform.EvalApply
2020/05/01 10:47:16 [DEBUG] sysdig_secure_rule_falco.thezebra_container_whitelist: applying the planned Update change
2020/05/01 10:47:16 [TRACE] GRPCProvider: ApplyResourceChange
2020/05/01 10:47:16 [DEBUG] sysdig_secure_rule_falco.thezebra_container_whitelist: apply errored, but we're indicating that via the Error pointer rather than returning it: {"errors":[{"reason":"system.error","message":"Sorry, something really bad happened with your request (traceId: 79d254a352fa3baf)."}]}
2020/05/01 10:47:16 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2020/05/01 10:47:16 [TRACE] <root>: eval: *terraform.EvalWriteState
2020/05/01 10:47:16 [TRACE] EvalWriteState: recording 0 dependencies for sysdig_secure_rule_falco.thezebra_container_whitelist
2020/05/01 10:47:16 [TRACE] EvalWriteState: writing current state object for sysdig_secure_rule_falco.thezebra_container_whitelist
2020/05/01 10:47:16 [TRACE] <root>: eval: *terraform.EvalApplyProvisioners
2020/05/01 10:47:16 [TRACE] EvalApplyProvisioners: sysdig_secure_rule_falco.thezebra_container_whitelist is not freshly-created, so no provisioning is required
2020/05/01 10:47:16 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2020/05/01 10:47:16 [TRACE] <root>: eval: *terraform.EvalWriteState
2020/05/01 10:47:16 [TRACE] EvalWriteState: recording 0 dependencies for sysdig_secure_rule_falco.thezebra_container_whitelist
2020/05/01 10:47:16 [TRACE] EvalWriteState: writing current state object for sysdig_secure_rule_falco.thezebra_container_whitelist
2020/05/01 10:47:16 [TRACE] <root>: eval: *terraform.EvalIf
2020/05/01 10:47:16 [TRACE] <root>: eval: *terraform.EvalIf
2020/05/01 10:47:16 [TRACE] <root>: eval: *terraform.EvalWriteDiff
2020/05/01 10:47:16 [TRACE] <root>: eval: *terraform.EvalApplyPost
2020/05/01 10:47:16 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: {"errors":[{"reason":"system.error","message":"Sorry, something really bad happened with your request (traceId: 79d254a352fa3baf)."}]}
2020/05/01 10:47:16 [ERROR] <root>: eval: *terraform.EvalSequence, err: {"errors":[{"reason":"system.error","message":"Sorry, something really bad happened with your request (traceId: 79d254a352fa3baf)."}]}
2020/05/01 10:47:16 [TRACE] [walkApply] Exiting eval tree: sysdig_secure_rule_falco.thezebra_container_whitelist
2020/05/01 10:47:16 [TRACE] vertex "sysdig_secure_rule_falco.thezebra_container_whitelist": visit complete
2020/05/01 10:47:16 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2020/05/01 10:47:16 [TRACE] dag/walk: upstream of "provider.sysdig (close)" errored, so skipping
2020/05/01 10:47:16 [TRACE] dag/walk: upstream of "root" errored, so skipping
Error: {"errors":[{"reason":"system.error","message":"Sorry, something really bad happened with your request (traceId: 79d254a352fa3baf)."}]}
```

Can we use the `traceId` somehow to uncover why it's breaking?

**Comment by tembleking** [comment] 2020-05-03 11:47
Hi @heydonovan, thanks for reporting it, I'll take a look at it ASAP.

**Comment by tembleking** [comment] 2020-05-03 11:53
I couldn't reproduce it, may I see the new and the previous condition for the rule?

**Comment by tembleking** [comment] 2020-05-08 18:20
Hello @heydonovan, thanks for your patience.
I believe this issue is solved by https://github.com/draios/terraform-provider-sysdig/commit/ea8c0e58e059520fd493788205a499265c319fe4, can you try it out please? 
If it works, we will create a new release ASAP.

**Comment by tembleking** [comment] 2020-05-12 09:41
I am closing this issue, if there is any other problem with it, don't hesitate to open it again. :slightly_smiling_face:

**Closed by tembleking** 2020-05-12 09:41 UTC
Labels: bug
